application: my-todo-list-194516
version: 1
runtime: python27
api_version: 1
threadsafe: false

# [START handlers]
handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: todo.py
# [END handlers]